function calculateTimestamps(durationInMinutes, remainingStops) {

  const currentTime = new Date();
  const interval = durationInMinutes / remainingStops;

  const timestamps = [];
  for (let i = 1; i <= remainingStops; i++) {
    const time = new Date(currentTime.getTime() + i * interval * 60000);
    timestamps.push(time.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }));
  }

  return timestamps;
}

export const tmtBusStops = [
  [
      "PAWAR NAGAR",
      "MUNICIPAL SCHOOL",
      "EDENWOOD",
      "LOKPURAM",
      "VASANT VIHAR",
      "JAWAHAR NAGAR",
      "GANDHI NAGAR",
      "VOLTAS",
      "SUBHASH NAGAR",
      "OSWAL PARK",
      "MAJIWADA NAKA",
      "MUKTAI NAGAR",
       "GOKUL NAGAR", 
     "UTHALSAR NAKA",  
     "CIVIL HOSPITAL", 
      "CENTRAL MAIDAN",
      "COURTNAKA",
      "TALAO PALI",
      "THANE STATION"
  ],
  [
    "ANAND NAGAR",
    "VIJAY NAGARI",
    "WAGHBIL",
    "DONGRI PADA",
    "PATLI PADA",
    "AZAD NAGAR",
    "MULLA BAGH",
    "MANPADA",
    "LOCKIM COMPANY",
    "HIDE PARK",
    "KAPURBAWDI",
    "ASHAPURA MANDIR",
    "MAJIWADA",
    "MUKTAI NAGAR",
    "GOKUL NAGAR",
    "CENTRAL MAIDAN",
    "COURT NAKA",
    "CIVIL COURT",
    "TALAV PALI",
    "THANE STATION"
    ],
    [ "VRUNDAVAN SOCIETY",
      "SHREERANG SOCIETY",
      "DESAI BANGLA",
      "ABHIRUCHI",
      "HOLY CROSS SCHOOL",
      "POLICE LINE",
      "CENTRAL MAIDAN",
      "COURT NAKA",
      "CIVIL COURT",
      "TALAV PALI",
      "THANE STATION"
    ],
    ["BORIVADE GAON",
      "VIJAY NAGARI",
    "WAGHBIL",
    "DONGRI PADA",
    "PATLI PADA",
    "AZAD NAGAR",
    "MULLA BAGH",
    "MANPADA",
    "LOCKIM COMPANY",
    "HIDE PARK",
    "KAPURBAWDI",
    "ASHAPURA MANDIR",
    "MAJIWADA",
    "MUKTAI NAGAR",
    "GOKUL NAGAR",
    "CENTRAL MAIDAN",
    "COURT NAKA",
    "CIVIL COURT",
    "TALAV PALI",
    "THANE STATION"],
    [ "KASARVADAVALI",
      "SAINATH NAGAR",
      "ANAND NAGAR",
      "MUCHHALA COLLEGE",
      "BATATA COMPANY",
      "PANCHAMRIT",
    "WAGHBIL",
    "DONGRI PADA",
    "PATLI PADA",
    "AZAD NAGAR",
    "MULLA BAGH",
    "MANPADA",
    "LOCKIM COMPANY",
    "HIDE PARK",
    "KAPURBAWDI",
    "ASHAPURA MANDIR",
    "MAJIWADA",
    "MUKTAI NAGAR",
    "GOKUL NAGAR",
    "CENTRAL MAIDAN",
    "COURT NAKA",
    "CIVIL COURT",
    "TALAV PALI",
    "THANE STATION"],
    [ "PARSIK NAGAR",
      "VASTU ANAND",
      "VIMAL NAGAR",
      "RAJ PARK",
      "PREM NAGAR",
      "PARSIK SHIV MANDIR",
      "KHARIGAON NAKA",
      "DATTA WADI",
      "SUKUR PARK",
      "SAHYADRI SOCIETY",
      "MANISHA NAGAR",
      "KALWA BUS STATION",
      "COURT NAKA",
      "KANHAJI AGRH CHOWK",
      "R.T.O OFFICE",
      "CENTRAL MAIDAN",
      "COURT NAKA",
      "THANE STATION"],
      ["WAGHBIL",
    "DONGRI PADA",
    "PATLI PADA",
    "AZAD NAGAR",
    "MULLA BAGH",
    "MANPADA",
    "LOCKIM COMPANY",
    "HIDE PARK",
    "KAPURBAWDI",
    "ASHAPURA MANDIR",
    "MAJIWADA",
    "MUKTAI NAGAR",
    "GOKUL NAGAR",
    "CENTRAL MAIDAN",
    "COURT NAKA",
    "CIVIL COURT",
    "TALAV PALI",
    "THANE STATION"],
    [ "UPVAN",
      "SHIVAI NAGAR",
      "DEVDAYA NAGAR",
      "S.T. JUNA THAMBA",
      "BUILDING NO. 3",
      "VARTAK NAGAR NAKA",
      "J.K. GRAM",
      "CADBURY CO.",
      "PUJANI ESTATE",
      "KHOPAT",
      "NEW SHAKTI MILL",
      "SHISHU GYAN MANDIR",
      "CIVIL HOSPITAL",
      "CENTRAL MAIDAN",
      "COURT NAKA",
      "THANE STATION"]
];

export default calculateTimestamps
